# Generated by Django 3.1.7 on 2021-04-01 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210401_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='data_pub',
            new_name='date_pub',
        ),
    ]
